[project]
name = "stacks-multi-wallet-signature"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/Secure-KYC/stacks-multi-wallet-signature/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.stacks-multi-wallet-signature]
path = "contracts/stacks-multi-wallet-signature.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
